version: '3.8'

services:

  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: vegetablesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    image: vijetavernekar/ovs:${BUILD_NUMBER}
    container_name: ovs-container
    ports:
      - "9090:80"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
