replicaCount: 2

image:
  repository: ovs   # your docker image
  tag: latest

service:
  type: NodePort
  port: 80
  targetPort: 8080

containerPort: 8080
env:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ovsdb
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres

resources: {}
